version: '3.8'
services:
  db:
    image: mysql:8.4
    container_name: projectbi-db
    environment:
      MYSQL_ROOT_PASSWORD: hoang504901
      MYSQL_DATABASE: stock_bi
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  etl:
    build: .
    container_name: projectbi-etl
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: hoang504901
      DB_NAME: stock_bi
      API_KEY_FMP: TPTxrDMbZB96m9QtFClX8kGTsgub1WM3
      API_KEY_APV: 25L8UJNSALAN1R7G
    volumes:
      - .:/etl
    command: python run_all.py

volumes:
  db_data: